### ISSUE TITLE
Allow configuring the number of connections per shard

### ISSUE THREAD

**Issue by piodul** [scylladb/cql-stress#54]
It would be useful to test how Scylla behaves when there are lots of open CQL connections to each node. A rust driver session opens one connection per shard by default but it can be configured to open more, so this is just a matter of adding an appropriate commandline option.

The option should be added both to s-b and c-s frontends.

**Comment by muzarski** [comment]
Can we close this issue?

**Comment by piodul** [comment]
Yes. Next time, please add "Fixes: #54" (with an appropriate issue number, of course) to the description of the PR so that it is closed automatically.
