### ISSUE TITLE
incompatible CLI with cassandra-stress

### ISSUE THREAD

**Issue by soyacz** [scylladb/cql-stress#73]
cql-stress-cassandra-stress uses different CLI arguments for `-col` argument. To make it work need to switch `-col 'size=FIXED(128) n=FIXED(8)'` to  `-col 'size=FIXED(128) n=8'`
also for `-pop` arg it is used differently: `-pop seq=1..125000000` need to switch to `-pop 'dist=SEQ(1..125000000)'` in cql-stress

This makes replacement of c-s to cql-stress more cumbersome and leads to failures.

**Comment by avelanarius** [comment]
> also for -pop arg it is used differently: -pop seq=1..125000000 need to switch to -pop 'dist=SEQ(1..125000000)' in cql-stress

In the current master version of cql-stress this is already solved.

**Comment by avelanarius** [comment]
> To make it work need to switch -col 'size=FIXED(128) n=FIXED(8)' to -col 'size=FIXED(128) n=8'

... but this still is not fixed.
